// Code generated by listennotes/devtools/api-sdks/sync.py go. DO NOT EDIT.
package listennotes

func callSDKMethod(client HTTPClient, operation string, args map[string]string) (*Response, error) {
	switch operation {
	case "search":
		return client.Search(args)
	case "typeahead":
		return client.Typeahead(args)
	case "searchEpisodeTitles":
		return client.SearchEpisodeTitles(args)
	case "spellcheck":
		return client.SpellCheck(args)
	case "getRelatedSearches":
		return client.FetchRelatedSearches(args)
	case "getTrendingSearches":
		return client.FetchTrendingSearches(args)
	case "getBestPodcasts":
		return client.FetchBestPodcasts(args)
	case "getPodcastById":
		return client.FetchPodcastByID(args["id"], args)
	case "deletePodcastById":
		return client.DeletePodcast(args["id"], args)
	case "getEpisodeById":
		return client.FetchEpisodeByID(args["id"], args)
	case "getEpisodesInBatch":
		return client.BatchFetchEpisodes(args)
	case "getPodcastsInBatch":
		return client.BatchFetchPodcasts(args)
	case "getCuratedPodcastById":
		return client.FetchCuratedPodcastsListByID(args["id"], args)
	case "getGenres":
		return client.FetchPodcastGenres(args)
	case "getRegions":
		return client.FetchPodcastRegions(args)
	case "getLanguages":
		return client.FetchPodcastLanguages(args)
	case "justListen":
		return client.JustListen(args)
	case "getCuratedPodcasts":
		return client.FetchCuratedPodcastsLists(args)
	case "getPodcastRecommendations":
		return client.FetchRecommendationsForPodcast(args["id"], args)
	case "getEpisodeRecommendations":
		return client.FetchRecommendationsForEpisode(args["id"], args)
	case "submitPodcast":
		return client.SubmitPodcast(args)
	case "getPlaylistById":
		return client.FetchPlaylistByID(args["id"], args)
	case "getPlaylists":
		return client.FetchMyPlaylists(args)
	case "getPodcastAudience":
		return client.FetchAudienceForPodcast(args["id"], args)
	case "getPodcastsByDomainName":
		return client.FetchPodcastsByDomain(args["domain_name"], args)
	case "createPlaylist":
		return client.CreatePlaylist(args)
	case "updatePlaylist":
		return client.UpdatePlaylist(args["id"], args)
	case "addPlaylistItem":
		return client.AddPlaylistItem(args["id"], args)
	case "deletePlaylistItem":
		return client.DeletePlaylistItem(args["id"], args["item_id"], args)
	case "updatePlaylistItemNotes":
		return client.UpdatePlaylistItemNotes(args["id"], args["item_id"], args)
	default:
		panic("unknown operation: " + operation)
	}
}
