// Code generated by listennotes/devtools/api-sdks/sync.py go. DO NOT EDIT.
package listennotes_test

import (
	"fmt"

	listennotes "github.com/ListenNotes/podcast-api-go/v3"
)

func ExampleHTTPClient_Search() {
	client := listennotes.NewClient("")
	response, err := client.Search(map[string]string{"q": "star wars", "sort_by_date": "0", "type": "episode", "offset": "0", "len_min": "10", "len_max": "30", "genre_ids": "68,82", "published_before": "1580172454000", "published_after": "0", "only_in": "title,description", "language": "English", "region": "", "safe_mode": "0", "unique_podcasts": "0", "interviews_only": "0", "sponsored_only": "0", "page_size": "10"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_Typeahead() {
	client := listennotes.NewClient("")
	response, err := client.Typeahead(map[string]string{"q": "star wars", "show_podcasts": "1", "show_genres": "1", "safe_mode": "0"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_SearchEpisodeTitles() {
	client := listennotes.NewClient("")
	response, err := client.SearchEpisodeTitles(map[string]string{"q": "Jerusalem Demsas on The Dispossessed"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_SpellCheck() {
	client := listennotes.NewClient("")
	response, err := client.SpellCheck(map[string]string{"q": "microsft stock"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_FetchRelatedSearches() {
	client := listennotes.NewClient("")
	response, err := client.FetchRelatedSearches(map[string]string{"q": "evergrande"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_FetchTrendingSearches() {
	client := listennotes.NewClient("")
	response, err := client.FetchTrendingSearches(nil)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_FetchBestPodcasts() {
	client := listennotes.NewClient("")
	response, err := client.FetchBestPodcasts(map[string]string{"genre_id": "93", "page": "2", "region": "us", "sort": "listen_score", "safe_mode": "0"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_FetchPodcastByID() {
	client := listennotes.NewClient("")
	response, err := client.FetchPodcastByID("4d3fe717742d4963a85562e9f84d8c79", map[string]string{"next_episode_pub_date": "1479154463000", "sort": "recent_first"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_DeletePodcast() {
	client := listennotes.NewClient("")
	response, err := client.DeletePodcast("4d3fe717742d4963a85562e9f84d8c79", map[string]string{"reason": "the podcaster wants to delete it"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_FetchEpisodeByID() {
	client := listennotes.NewClient("")
	response, err := client.FetchEpisodeByID("6b6d65930c5a4f71b254465871fed370", map[string]string{"show_transcript": "1"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_BatchFetchEpisodes() {
	client := listennotes.NewClient("")
	response, err := client.BatchFetchEpisodes(map[string]string{"ids": "c577d55b2b2b483c969fae3ceb58e362,0f34a9099579490993eec9e8c8cebb82"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_BatchFetchPodcasts() {
	client := listennotes.NewClient("")
	response, err := client.BatchFetchPodcasts(map[string]string{"ids": "3302bc71139541baa46ecb27dbf6071a,68faf62be97149c280ebcc25178aa731,37589a3e121e40debe4cef3d9638932a,9cf19c590ff0484d97b18b329fed0c6a", "rsses": "https://rss.art19.com/recode-decode,https://rss.art19.com/the-daily,https://www.npr.org/rss/podcast.php?id=510331,https://www.npr.org/rss/podcast.php?id=510331", "itunes_ids": "1457514703,1386234384,659155419", "spotify_ids": "3DDfEsKDIDrTlnPOiG4ZF4,4qDNe5Gvl1XxdLinUGEXrC,23NZCM4ik6o3UYkM473Itz", "show_latest_episodes": "1", "next_episode_pub_date": "1557394247000"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_FetchCuratedPodcastsListByID() {
	client := listennotes.NewClient("")
	response, err := client.FetchCuratedPodcastsListByID("SDFKduyJ47r", nil)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_FetchPodcastGenres() {
	client := listennotes.NewClient("")
	response, err := client.FetchPodcastGenres(map[string]string{"top_level_only": "1"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_FetchPodcastRegions() {
	client := listennotes.NewClient("")
	response, err := client.FetchPodcastRegions(nil)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_FetchPodcastLanguages() {
	client := listennotes.NewClient("")
	response, err := client.FetchPodcastLanguages(nil)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_JustListen() {
	client := listennotes.NewClient("")
	response, err := client.JustListen(nil)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_FetchCuratedPodcastsLists() {
	client := listennotes.NewClient("")
	response, err := client.FetchCuratedPodcastsLists(map[string]string{"page": "2"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_FetchRecommendationsForPodcast() {
	client := listennotes.NewClient("")
	response, err := client.FetchRecommendationsForPodcast("25212ac3c53240a880dd5032e547047b", map[string]string{"safe_mode": "0"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_FetchRecommendationsForEpisode() {
	client := listennotes.NewClient("")
	response, err := client.FetchRecommendationsForEpisode("254444fa6cf64a43a95292a70eb6869b", map[string]string{"safe_mode": "0"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_SubmitPodcast() {
	client := listennotes.NewClient("")
	response, err := client.SubmitPodcast(map[string]string{"rss": "https://feeds.megaphone.fm/committed", "email": "hello@example.com"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_FetchPlaylistByID() {
	client := listennotes.NewClient("")
	response, err := client.FetchPlaylistByID("m1pe7z60bsw", map[string]string{"type": "episode_list", "last_timestamp_ms": "0", "sort": "recent_added_first"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_FetchMyPlaylists() {
	client := listennotes.NewClient("")
	response, err := client.FetchMyPlaylists(map[string]string{"sort": "recent_added_first", "page": "1"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_FetchAudienceForPodcast() {
	client := listennotes.NewClient("")
	response, err := client.FetchAudienceForPodcast("25212ac3c53240a880dd5032e547047b", nil)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_FetchPodcastsByDomain() {
	client := listennotes.NewClient("")
	response, err := client.FetchPodcastsByDomain("nytimes.com", map[string]string{"page": "1"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_CreatePlaylist() {
	client := listennotes.NewClient("")
	response, err := client.CreatePlaylist(map[string]string{"name": "My favorite podcasts", "description": "Podcasts and episodes to revisit.", "visibility": "public", "type": "episode_list"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_UpdatePlaylist() {
	client := listennotes.NewClient("")
	response, err := client.UpdatePlaylist("m1pe7z60bsw", map[string]string{"name": "My favorite podcasts", "description": "Podcasts and episodes to revisit.", "visibility": "public", "type": "podcast_list"})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_AddPlaylistItem() {
	client := listennotes.NewClient("")
	response, err := client.AddPlaylistItem("m1pe7z60bsw", map[string]string{"episode_id": "e53e6992a5b7492f9ea6fcd85d9ad95f", "notes": "Worth a listen."})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_DeletePlaylistItem() {
	client := listennotes.NewClient("")
	response, err := client.DeletePlaylistItem("m1pe7z60bsw", "23", nil)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}

func ExampleHTTPClient_UpdatePlaylistItemNotes() {
	client := listennotes.NewClient("")
	response, err := client.UpdatePlaylistItemNotes("m1pe7z60bsw", "23", map[string]string{"notes": ""})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.ToJSON())
}
